kind: "CDN"
version: "1"
metadata:
    envTypes: [ "dev", "prod", "stage" ]
data:
  responseTransformations:
    rules:
      - name: "frame-security-policy-for-author"
        when:
            reqProperty: domain
            matches: "author-p10961-e\\d+\\.adobeaemcloud\\.com"
        actions:
          - type: set
            value:  frame-ancestors 'self' https://experience.adobe.com
            respHeader: Content-Security-Policy       
      - name: "set-samesite-none-for-login-token"
        when:
            respHeader: Set-Cookie
            matches: "login-token=.*"
        actions:
          - type: set
            respHeader: Set-Cookie
            value: { respHeader: Set-Cookie, transform: [ {op: 'replace', match: 'SameSite=(Lax|Strict|None)', replacement: 'SameSite=None'} ] } 
  originSelectors:
    rules:
      - name: select-edge-delivery-services-origin
        when:
          allOf:
            - reqProperty: tier
              equals: publish
            - reqProperty: path
              matches: "^(/index)"
        action:
          type: selectOrigin
          originName: aem-live
    origins:
      - name: aem-live
        domain: main--eaem-rde-eds-brand-seven--schoudry.aem.live            